import "@mlplanner/styles/globals.css";

import { Inter } from 'next/font/google'
import { type Metadata } from "next";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="pt-br" className={`${inter.className}`}>
      <body>{children}</body>
    </html>
  );
}
